### ISSUE TITLE
Riptide does not respect thread max-size despite being configured

### ISSUE THREAD

**Issue by mesut** [zalando/riptide#1642]
Riptide does not respect thread max-size despite being configured

## Description

Riptide takes `connections.max-per-route` as max thread if `connections.max-per-route` is greater than` threads.max-size`. 

```
riptide:
  defaults:
    threads:
      max-size: 15
    connections:
      time-to-live: 30 seconds
      max-per-route: 30 
```

## Expected Behavior
Riptide should configure threads.max-size as max thread for it thread pool.

## Actual Behavior
Riptide takes `connections.max-per-route` as max thread if `connections.max-per-route` is greater than` threads.max-size`. 

## Possible Fix
Not include `connections.max-per-route` in deciding what would be max thread when merging defaults. If no max-thread is configured, then it should take default max thread as max thread

https://github.com/zalando/riptide/blob/main/riptide-spring-boot-autoconfigure/src/main/java/org/zalando/riptide/autoconfigure/Defaulting.java#L105

## Steps to Reproduce
1. Configure your riptide to have `connections.max-per-route` is greater than ` threads.max-size`
2. 
3. 
4.

## Your Environment

* Version used: 4.0.0
