### ISSUE TITLE
Resilience: Plugin configuration

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/riptide#229]
Instead of just listing plugins, allow for a deeper integration:

- [x] `keep-original-stack-trace: true`
- [x] `detect-transient-faults: true`
- [x] `failsafe:`:

```yaml
rest.clients:
  example:
    failsafe: # only needed if we keep hystrix as an alternative, not sure if I actually want to
      retry:
        fixed-delay: 1 second
        backoff:
          delay: 500 milliseconds
          max-delay: 3 seconds
          delay-factor: 2 # default
        max-retries: 3
        max-duration: 5 seconds
        jitter-factor: 0.1
        jitter: 100 milliseconds
      circuit-breaker:
        failure-threshold: 5
        delay: 1 minute
        success-threshold: 5
```
