### ISSUE TITLE
Resilience: Timeout

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/riptide#233]
Given Java 9 support, having a `TimeoutPlugin` would allow us to use [`CompletableFuture.orTimeout(long, TimeUnit)`](http://download.java.net/java/jdk9/docs/api/java/util/concurrent/CompletableFuture.html#orTimeout-long-java.util.concurrent.TimeUnit-). The timeout would logically applied globally and would include any retries and individual connection and socket timeouts.

@lukasniemeier-zalando Your thoughts?

Individual requests can of course apply a lower timeout on a per call basis:

```java
http.get("/")
  .dispatch(..)
  .orTimeout(1, SECONDS);
```

Configuration support could look like:

```yaml
riptide.clients:
  example:
    base-url: http://example.com
    global-timeout: 1 second # or just
    timeout: 1 second
```
