### ISSUE TITLE
jacksonObjectMapper not found

### ISSUE THREAD

**Issue by jmatusewicz-bringmeister** [zalando/riptide#307]
After defining a riptide client in the application.yml the application start fails due to missing bean definition `jacksonObjectMapper`

```
riptide:
  defaults:
    connection-timeout: 1 seconds
    socket-timeout: 2 seconds
    connection-time-to-live: 30 seconds
    record-metrics: true
  clients:
    myclient:
      base-url: https://example.org
```

```
2017-12-05 16:10:41,627 {WARN} [restartedMain] [] [org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext] Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'myclientHttpMessageConverters': Cannot create inner bean '(inner bean)#1bd5293e' of type [org.springframework.http.converter.json.MappingJackson2HttpMessageConverter] while setting constructor argument with key [1]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#1bd5293e': Cannot resolve reference to bean 'jacksonObjectMapper' while setting constructor argument; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'jacksonObjectMapper' available
```
