### ISSUE TITLE
Request hangs when retries or circuit breakers are configured

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/riptide#319]
## Behaviour

Multiple users reported the following behaviour:

> The application hangs forever when making a remote request.

All users had two things in common. They had retries and/or a circuit breaker configured:
```yaml
riptide:
  clients:
    example:
      base-url: http://httpbin.org/
      retry:
        fixed-delay: 50 milliseconds
      circuit-breaker:
        failure-threshold: 3 out of 5
```

They also made use of `@EnableScheduling` and `@Scheduled` annotation.

## Cause

Retries and circuit breaker require a scheduler (`ScheduledThreadPoolExecutor`), so the `riptide-spring-boot-starter` registers one per client (1 in this case). But then Spring does the following:

> By default, will be searching for an associated scheduler definition: either a unique TaskScheduler bean in the context, or a TaskScheduler bean named "taskScheduler" otherwise; the same lookup will also be performed for a ScheduledExecutorService bean. If neither of the two is resolvable, a local single-threaded default scheduler will be created and used within the registrar.
>
> https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/scheduling/annotation/EnableScheduling.html

In other words, Spring will silently use our scheduler for `@Scheduled` methods and since our scheduler is single threaded, there is no thread left for the retries/circuit breaker.

## Possible workarounds

1. Register a custom scheduler called `taskScheduler`:
```java
@Bean(destroyMethod = "shutdown")
public ScheduledExecutorService taskScheduler() {
    return Executors.newScheduledThreadPool(Runtime.getRuntime().availableProcessors());
}
```
2. Use the [Tracer Spring Boot Starter](https://github.com/zalando/tracer#spring-boot-starter), as it will register such a scheduler for you (+ it will enable call tracing):
```xml
<dependency>
	<groupId>org.zalando</groupId>
	<artifactId>tracer-spring-boot-starter</artifactId>
	<version>0.11.2</version>
</dependency>
```
3. Define more than one client in the `application.yaml` so that no unique scheduler exists in the context, which in turn forces Spring to create a new scheduler ([be aware, that one also has a size of 1](https://stackoverflow.com/questions/29796651/what-is-the-default-scheduler-pool-size-in-spring-boot))
```yaml
foo:
  circuit-breaker:
    failure-threshold: 1 out of 10
```
