### ISSUE TITLE
Base url configuration is using only scheme and hostname 

### ISSUE THREAD

**Issue by vijayparashar12** [zalando/riptide#393]
we are using riptide-spring-boot-starter for our reservation client is not using `/api` path from the base url 
## Description
our client setting
```
riptide:
  clients:
    reservation:
      base-url: https://unit-reservation.wpi-dev.zalan.do/api
    movementService:
      base-url: https://movement-service-dev.logistics-test.zalan.do
```

```
http
    .get("/sites/moenchengladbach/unit-types/item/reservations/ISga5mc2TTFDF6xiHPr22eJyO7wfjQrt")
    .header(HttpHeaders.AUTHORIZATION, String.format("Bearer %s", token.get(TokenId.RESOURCE_LAYER.name())))
     .dispatch(Navigators.series(),
                        on(HttpStatus.Series.SUCCESSFUL).call(GetReservationResponse.class, capture),
                        anySeries().call(ProblemRoute.problemHandling())
                )
    .thenApply(capture);
```
java.lang.AssertionError: Request URI 
 
## Expected Behavior
Request goes out with following URI

Expected :https://unit-reservation.wpi-dev.zalan.do/api/sites/moenchengladbach/unit-types/item/reservations/ISga5mc2TTFDF6xiHPr22eJyO7wfjQrt

## Actual Behavior
Actual   :https://unit-reservation.wpi-dev.zalan.do/sites/moenchengladbach/unit-types/item/reservations/ISga5mc2TTFDF6xiHPr22eJyO7wfjQrt

## Steps to Reproduce

1. Add client base url with some path
2. try ger request with  the client
3.  check outgoing url

## Your Environment

* Version used: 2.6.1
* Link to your project:

**Comment by whiskeysierra** [comment]
By default Riptide strictly implements [RFC 3986: Uniform Resource Identifier (URI)](https://tools.ietf.org/html/rfc3986#section-5.4), which requires that absolute URIs are resolved exactly the way you experience. Please note that `/sites/moenchengladbach/unit-types/item/reservations/ISga5mc2TTFDF6xiHPr22eJyO7wfjQrt` is an absolute URI, since it starts with a `/`.

There are two options to make it work:

1. Change your request path from absolute to relative, e.g.:
    `sites/moenchengladbach/unit-types/item/reservations/ISga5mc2TTFDF6xiHPr22eJyO7wfjQrt`
2. Change the [URL resolution](https://github.com/zalando/riptide/blob/master/docs/uri-resolution.md) from `rfc` (default) to `append`. This will give you the behavior that you expect:

```yaml
riptide:
  defaults:
    url-resolution: append
```

I'm closing the issue. If there is still an issue, don't hesitate to respond and/or re-open it.
