### ISSUE TITLE
SpringBoot2xSettingsParser fails to resolve placeholders

### ISSUE THREAD

**Issue by mazenmelouk** [zalando/riptide#488]
## Description
When using riptide 2.8.1, and defining scopes as follows 
```yaml
riptide:
  clients:
    user-detail:
      oauth.scopes: uid, ${SCOPE:service.read}
```
The scopes are read as is without being resolved!
With a bit of debugging it seems this line(https://github.com/zalando/riptide/blob/7ee3f0917b213303d93d36fdb9c0cba524897643/riptide-spring-boot-2.x-support/src/main/java/org/zalando/riptide/spring/SpringBoot2xSettingsParser.java#L24)
It constructs a binder with no PlaceHolderResolver.
