### ISSUE TITLE
OpenTracing support

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/riptide#509]
## Detailed Description

Add OpenTracing integration that e.g. allows to add retry count as a tag to spans.

## Context

Instrumenting the underlying Apache Http Client is a good enough solution for most, but a deeper integration allows for more sophisticated use cases (like retry count).

## Possible Implementation

- [x] `riptide-opentracing` module
  - [x] `OpenTracingPlugin` 
  - [x] plugin that creates a span for one logical request
  - [x] `OpenTracingRetryListener` which set's a retry count tag
  - [x] Support for span decorator?
    - [x] Tags https://github.com/opentracing/specification/blob/master/semantic_conventions.md
  - [x] Operation Name generator?
    - [x] Type-safe attributes to be passed from call-site to plugins (transported as part of request arguments)
- [x] `riptide-spring-boot-autoconfigure`
  - [x] plugin needs to be registered directly after/before timeout plugin (auto configuration)
  - [x] instrument executor and scheduler using [opentracing-concurrent](https://github.com/opentracing-contrib/java-concurrent)
  - [x] instrument Apache Http Client using [jaeger-apachehttpclient](https://github.com/jaegertracing/legacy-client-java/tree/master/jaeger-apachehttpclient) without dependency to jaeger!
    - [x] Propagate tags?
  - [x] Set client id as tag?
  - [x] Degree of configurability?

### Example Configuration

```yaml
riptide:
  defaults:
    tracing:
      enabled: true
      tags:
        account: ${CDP_TARGET_INFRASTRUCTURE_ACCOUNT}
        zone: ${CDP_TARGET_REGION}
        artifact_version: ${CDP_BUILD_VERSION}
        deployment_id: ${CDP_DEPLOYMENT_ID}
      propagate-flow-id: true
        
  clients:
    exchange-rate:
      tracing:
        tags:
          peer.service: exchange-rate-service
        propagate-flow-id: false
```

## Your Environment

* Version used:
* Link to your project:
