### ISSUE TITLE
Configure caching

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/riptide#558]
## Detailed Description

It would be nice if we could configure caching per client within the `application.yml`.

## Context

Enabling users to use caching out of the box for simple use cases.

## Possible Implementation

https://hc.apache.org/httpcomponents-client-ga/tutorial/html/caching.html

```yaml
riptide:
  clients:
    example:
      caching:
        shared: false
        directory: /var/cache/http
        max-object-size: 8192
        max-cache-entries: 1000
        heuristic:
          coefficient: 0.1
          default-life-time: 30 minutes
          
```
