### ISSUE TITLE
Chaos

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/riptide#616]
## Detailed Description

Add support for chaos in the form of automated failure injection.

## Context

https://medium.com/netflix-techblog/fit-failure-injection-testing-35d8e2a9bb2
https://medium.com/netflix-techblog/the-netflix-simian-army-16e57fbab116

## Possible Implementation

- [x] New module `riptide-chaos`
- [x] New plugin `ChaosPlugin` **or**
- [x] Three individual plugins, one for each failure injection type
- [x] Different failure injections
  - [x] Latency
    - [x] sleep vs. schedule?
  - [x] Error Response (e.g. status code 500)
  - [x] Exception, e.g. fake IO exceptions

### Possible configuration

```yaml
riptide:
  clients:
    example:
      chaos:
        latency:
          enabled: true
          delay: 1 second
          probability: 0.01
        error-responses:
          enabled: true
          status-codes: [500, 503]
          probability: 0.001
        exceptions:
          enabled: true
```
